# we need pass 2 varibles
  #1. component
  #2. environment

- name:  configure {{ component }} server
  hosts: all
  become: yes # remote
  vars_files:
  - "variables-{{ environment }}.yaml" # anslible server
  roles:
  - " {{ component }}"
